### ISSUE TITLE
載了對應的模擬器但出現找不到支援的模擬器

### ISSUE THREAD

**Issue by JueXiuHuang** [PoH98/Valkyrie-Crusade-Bot#3]
如標題，目前我使用的是夜神模擬器，emulator資料夾下的ini檔也有改成Nox了，請問這個問題要如何解決呢QQ

**Comment by PoH98** [comment]
我会尽快的修复好Bug，主要是因为之前一直没人用所以我就没什么测试所有其他模拟器是否可以运行

**Comment by PoH98** [comment]
更新了新版本修复无法检测模拟器问题
